# === Name === #
name: TwoLayerFC

# === Architecture === #
arch: TwoLayerFC
hidden_size: 500
bias: True

# ===== Dataset ===== #
data_dir: ../data/
dataset: MNIST

# ===== Network training config ===== #
num_epochs: 10
batch_size: 128
freeze_weights: True
seed: 1
log_interval: 200
submask_size: 1
metric: "loss"
pruning_strategy: "activations_and_weights"
how_to_prune: "layer"
save_plot_data: True
start_from_nothing: True

# ===== Hardware setup ===== #
num_workers: 8
gpu: 0
