# === Name === #
name: TwoLayerFC

# === Architecture === #
arch: TwoLayerFC
hidden_size: 500
bias: True

# ===== Dataset ===== #
data_dir: ../data/
dataset: MNIST

# ===== Network training config ===== #
num_epochs: 25
batch_size: 256
freeze_weights: True
seed: 1
log_interval: 200
submask_size: 1
metric: "loss"
pruning_strategy: "weights"
how_to_prune: "layer"
save_plot_data: True
start_from_nothing: False 
load_ckpt: "./results/TwoLayerFC/prune_activations_and_weights_exp3/checkpoints/best_model.state"

# ===== Hardware setup ===== #
num_workers: 8
gpu: 0
