# === Name === #
name: TwoLayerFC

# === Architecture === #
arch: TwoLayerFC
hidden_size: 500
bias: True

# ===== Dataset ===== #
data_dir: ../data/
dataset: MNIST

# ===== Network training config ===== #
num_epochs: 10 
batch_size: 128
freeze_weights: True
seed: 1
log_interval: 200
submask_size: 1
metric: "loss"
pruning_strategy: "simulated_annealing"
td: 0.999
temp: 100000
max_iter: 100000

# ===== Hardware setup ===== #
num_workers: 4
gpu: 0
