# Edge-popup version
# ksreenivsan: rolling back EP config to original Ramanujan config

algo: 'ep'

# Architecture
arch: Conv4

# ===== Dataset ===== #
dataset: CIFAR10
name: conv4_ep_sc

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 150
wd: 0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: 0.5
init: signed_constant
scale_fan: True

# ===== Hardware setup ===== #
workers: 4
gpu: 3
