# Hypercube optimization
algo: 'hc'

# Architecture
arch: Conv4

# ===== Dataset ===== #
dataset: CIFAR10
name: conv4_sc_unsigned

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.01
#lr_policy: None

# ===== Network training config ===== #
epochs: 150 # 150
wd: 0.0 #0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: 0.0
init: signed_constant
fixed_init: True
score_init: bern
scale_fan: False #True


# ===== Rounding ===== #
round: naive
hc_warmup: 150 #30
hc_period: 10 #10
noise: True
noise_ratio: 0.00

# ===== Hardware setup ===== #
workers: 4
