# Edge-popup version
algo: 'training'

# Architecture
arch: Conv4Normal

# ===== Dataset ===== #
dataset: CIFAR10
name: conv4_standard_training

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.001
lr_policy: constant_lr

# ===== Network training config ===== #
epochs: 150 #100
wd: 0.0001
momentum: 0.9
batch_size: 128

weight_training: True

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1
init: kaiming_normal
scale_fan: True

# ===== Hardware setup ===== #
workers: 4
gpu: 3
